# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 01:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.FloatField(verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_order', models.IntegerField(verbose_name='Total Order')),
                ('payment_method', models.CharField(choices=[('COD', 'Cash on Delivery'), ('NB', 'Net banking'), ('CP', 'Card Payment'), ('WA', 'Wallet')], max_length=2)),
                ('status', models.CharField(choices=[('PE', 'Order Pending'), ('AP', 'Order Approved'), ('SH', 'Order Shipped'), ('DE', 'Order Delivered'), ('CA', 'Order Cancelled'), ('RE', 'Order Return')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders'),
        ),
    ]
