# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('NB', 'Net banking'), ('CP', 'Card Payment'), ('WA', 'Wallet')], max_length=3),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('PE', 'Order Pending'), ('AP', 'Order Approved'), ('SH', 'Order Shipped'), ('DE', 'Order Delivered'), ('CA', 'Order Cancelled'), ('RE', 'Order Return')], max_length=3),
        ),
    ]
